/******TICKET******/
--SELECT (LIST)
-- 티켓 상품 전체보기
SELECT * FROM TICKET;
--티켓 가격별
SELECT TI_PRICE FROM TICKET;
--지역별 검색
SELECT * FROM TICKET WHERE TI_TITLE LIKE '%부산%';

-- TICKET 수정
UPDATE TICKET SET TI_TITLE='수정', TI_PRICE=11111, TI_INFO='수정수정', TI_NOTICE='네네네', TI_COUNT=1, CITY_NO=1
WHERE TI_NO=1;
--TICKET 수량 수정
UPDATE TICKET SET TI_COUNT=100 WHERE TI_NO=1;
--TICKET 삭제
DELETE FROM TICKET WHERE TI_NO=1;
COMMIT;



/********************************************/
--판매순 -- JOIN -- PAYMENT 후에 JOIN

/************TICKET_RESERVE************/
--내 예약 조회
SELECT  TI_RS_NO,TI_RS_DATE,TI_RS_QTY,TI_RS_MSG, 
        T.TI_NO, TI_TITLE, TI_DATE, TI_PRICE, TI_INFO, TI_NOTICE, TI_COUNT, CITY_NO, TR.USER_ID
FROM TICKET_RESERVE TR
JOIN TICKET T
ON T.TI_NO = TR.TI_NO
WHERE USER_ID='user1';

/****예약 수정****/

UPDATE TICKET_RESERVE SET TI_RS_DATE='2023-04-27', TI_RS_QTY=10, TI_RS_MSG='수정사항입니다....2'
WHERE TI_RS_NO=1;

/****예약 삭제****/
DELETE FROM TICKET_RESERVE WHERE TI_RS_NO=1;


/****TICKET_REVIEW****/
--티켓번호로 리뷰 보기
SELECT TI_REVIEW_NO, TI_REVIEW_DATE,TI_REVIEW_TITLE, TI_REVIEW_CONTENT,
       T.TI_NO, USER_ID
FROM TICKET_REVIEW TR
JOIN TICKET T
ON T.TI_NO=TR.TI_NO
WHERE TR.TI_NO=1;

--내가 쓴 리뷰 보기 
SELECT TI_REVIEW_NO, TI_REVIEW_DATE,TI_REVIEW_TITLE, TI_REVIEW_CONTENT,
       T.TI_NO, USER_ID
FROM TICKET_REVIEW TR
JOIN TICKET T
ON T.TI_NO=TR.TI_NO
WHERE USER_ID='user1';

SELECT*FROM TICKET_REVIEW;
--리뷰 수정
UPDATE TICKET_REVIEW SET TI_REVIEW_TITLE='수정리뷰', TI_REVIEW_CONTENT='후기수정하고있음'
WHERE TI_REVIEW_NO=1;

--리뷰 삭제
DELETE FROM TICKET_REVIEW WHERE TI_REVIEW_NO=1;
