/******TICKET******/
--SELECT (LIST)
-- 티켓 상품 전체보기
SELECT * FROM TICKET;
--티켓 가격별
SELECT TI_PRICE FROM TICKET;
--키워드로 검색
SELECT * FROM TICKET WHERE TI_TITLE LIKE '%부산%';
--지역별 검색
SELECT TI_NO, TI_TITLE, TI_DATE, TI_PRICE, TI_INFO, TI_NOTICE, TI_COUNT,
       T.CITY_NO, CITY_NAME, LATITUDE, LONGITUDE
FROM TICKET T
JOIN CITY C
ON T.CITY_NO = C.CITY_NO
WHERE T.CITY_NO=1;

-- TICKET 수정
UPDATE TICKET SET TI_TITLE='수정', TI_PRICE=11111, TI_INFO='수정수정',
                  TI_NOTICE='네네네', TI_COUNT=1, CITY_NO=1
WHERE TI_NO=1;
--TICKET 삭제
DELETE FROM TICKET WHERE TI_NO=1;
COMMIT;



/********************************************/
--판매순 -- JOIN -- PAYMENT 후에 JOIN

/************TICKET_RESERVE 티켓 예약************/
--내 예약 조회
SELECT * FROM TICKET_RESERVE WHERE USER_ID='user1';
--티켓 예약 상세 보기
SELECT TI_RS_NO, TI_RS_DATE, TI_RS_QTY, TI_RS_MSG, USER_ID, TR.TI_NO,
       TI_TITLE, TI_DATE, TI_PRICE, TI_INFO, TI_NOTICE, TI_COUNT, CITY_NO
FROM TICKET_RESERVE TR
JOIN TICKET T
ON TR.TI_NO = T.TI_NO
where TI_RS_NO=1;

/****예약 삭제****/
DELETE FROM TICKET_RESERVE WHERE TI_RS_NO=1;


/****TICKET_REVIEW 티켓 후기****/
--티켓번호로 리뷰 보기 --join
SELECT TR.TI_REVIEW_NO, TI_REVIEW_DATE,TI_REVIEW_TITLE, TI_REVIEW_CONTENT, TI_NO, USER_ID,
       TI_RV_IMG_NO, TI_REVIEW_IMG_URL
FROM TICKET_REVIEW TR
JOIN TICKET_IMG TMG
ON TR.TI_REVIEW_NO=TMG.TI_REVIEW_NO
WHERE TI_NO=1;

--내가 쓴 리뷰 보기
SELECT * FROM TICKET_REVIEW WHERE USER_ID='user1';

--리뷰 수정
UPDATE TICKET_REVIEW SET TI_REVIEW_TITLE='수정리뷰', TI_REVIEW_CONTENT='후기수정하고있음'
WHERE TI_REVIEW_NO=1;

--리뷰 삭제
DELETE FROM TICKET_REVIEW WHERE TI_REVIEW_NO=1;


/****TICKET_IMG 티켓 후기 이미지****/

SELECT * FROM TICKET_IMG;
--리뷰 사진 보기
SELECT * FROM TICKET_IMG WHERE TI_REVIEW_NO=1;
--리뷰 사진 수정
UPDATE TICKET_IMG SET TI_REVIEW_IMG_URL='UPDATE.JPG' WHERE TI_RV_IMG_NO=6;
--리뷰 사진 삭제
DELETE FROM TICKET_IMG WHERE TI_RV_IMG_NO=1;

/****TICKET_WISHLIST****/
--티켓 위시리스트 전체 보기
SELECT * FROM WISHLIST;

--내 위시리스트 보기
SELECT * FROM WISHLIST WHERE USER_ID='user1';

