--TICKET 티켓 상품
INSERT INTO TICKET (TI_NO, TI_TITLE,TI_DATE,TI_PRICE,TI_INFO,TI_NOTICE,TI_COUNT,CITY_NO)
VALUES (TICKET_TI_NO_SEQ.NEXTVAL,'서울로 가보 자고', SYSDATE, 10000, '이 티켓은 서울로 가는 티켓', '눈 뜨고 코 베이지 않게 주의 하세요.',default,1);
INSERT INTO TICKET (TI_NO, TI_TITLE,TI_DATE,TI_PRICE,TI_INFO,TI_NOTICE,TI_COUNT,CITY_NO)
VALUES (TICKET_TI_NO_SEQ.NEXTVAL,'부산으로 가보 자고', SYSDATE, 20000, '이 티켓은 부산으로 가는 티켓', '갈매기를 주의 하세요.',default,2);
INSERT INTO TICKET (TI_NO, TI_TITLE,TI_DATE,TI_PRICE,TI_INFO,TI_NOTICE,TI_COUNT,CITY_NO)
VALUES (TICKET_TI_NO_SEQ.NEXTVAL,'제주도로 가보 자고', SYSDATE, 40000, '이 티켓은 제주도로 가는 티켓 ', '돌아 오기 싫을 수 있으니 주의 하세요.',default,3);
INSERT INTO TICKET (TI_NO, TI_TITLE,TI_DATE,TI_PRICE,TI_INFO,TI_NOTICE,TI_COUNT,CITY_NO)
VALUES (TICKET_TI_NO_SEQ.NEXTVAL,'어디 든지 가보 자고', SYSDATE, 99999, '이 티켓은 어디든 가는 티켓', '어디로 갈지 모르니 주의 하세요.',default,4);


--TICKET_RESERVE 티켓 예약
INSERT INTO TICKET_RESERVE (TI_RS_NO, TI_RS_DATE, TI_RS_QTY, TI_RS_MSG, TI_NO, USER_ID) VALUES (TICKET_RESERVE_TI_RS_NO_SEQ.NEXTVAL,'2023-03-26', 1,'요청사항입니다....',1,'user1');
INSERT INTO TICKET_RESERVE (TI_RS_NO, TI_RS_DATE, TI_RS_QTY, TI_RS_MSG, TI_NO, USER_ID) VALUES (TICKET_RESERVE_TI_RS_NO_SEQ.NEXTVAL,'2023-04-26', 3,'요청사항입니다....2',2,'user2');
INSERT INTO TICKET_RESERVE (TI_RS_NO, TI_RS_DATE, TI_RS_QTY, TI_RS_MSG, TI_NO, USER_ID) VALUES (TICKET_RESERVE_TI_RS_NO_SEQ.NEXTVAL,'2023-03-31', 4,'요청사항입니다....3',3,'user3');

--TICKET_REVIEW 티켓 리뷰
INSERT INTO TICKET_REVIEW (TI_REVIEW_NO, TI_REVIEW_DATE, TI_REVIEW_TITLE, TI_REVIEW_CONTENT, TI_NO, USER_ID) VALUES (TICKET_REVIEW_TI_REVIEW_NO_SEQ.NEXTVAL,'2023-03-27','티켓예약1번후기작성', '서울로 가보자고는 짱이다.',1,'user1');
INSERT INTO TICKET_REVIEW (TI_REVIEW_NO, TI_REVIEW_DATE, TI_REVIEW_TITLE, TI_REVIEW_CONTENT, TI_NO, USER_ID) VALUES (TICKET_REVIEW_TI_REVIEW_NO_SEQ.NEXTVAL, '2023-04-27','티켓2번후기작성','부산으로 가보자고 후기입니다.',2,'user2');

--TICKET_WISHLIST 티켓 위시리스트
INSERT INTO TICKET_WISHLIST (TI_WISH_NO, USER_ID, WISH_NO, TI_NO) VALUES(TICKET_WISHLIST_TI_WISH_NO_SEQ.NEXTVAL,'user1',1,1);
INSERT INTO TICKET_WISHLIST (TI_WISH_NO, USER_ID, WISH_NO, TI_NO) VALUES(TICKET_WISHLIST_TI_WISH_NO_SEQ.NEXTVAL,'user1',2,1);
INSERT INTO TICKET_WISHLIST (TI_WISH_NO, USER_ID, WISH_NO, TI_NO) VALUES(TICKET_WISHLIST_TI_WISH_NO_SEQ.NEXTVAL,'user2',3,2);
INSERT INTO TICKET_WISHLIST (TI_WISH_NO, USER_ID, WISH_NO, TI_NO) VALUES(TICKET_WISHLIST_TI_WISH_NO_SEQ.NEXTVAL,'user1',4,3);
INSERT INTO TICKET_WISHLIST (TI_WISH_NO, USER_ID, WISH_NO, TI_NO) VALUES(TICKET_WISHLIST_TI_WISH_NO_SEQ.NEXTVAL,'user3',5,4);

--TICKET_IMG 티켓 사진
INSERT INTO TICKET_IMG (TI_RV_IMG_NO, TI_REVIEW_IMG_URL,TI_REVIEW_NO) VALUES(TOUR_IMG_TO_IMG_NO_SEQ.NEXTVAL,'DEFAULT.JPG',1);
INSERT INTO TICKET_IMG (TI_RV_IMG_NO, TI_REVIEW_IMG_URL,TI_REVIEW_NO) VALUES(TOUR_IMG_TO_IMG_NO_SEQ.NEXTVAL,'DEFAULT.JPG',2);